name: 490F
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6.9
  - numba=0.45.1
  - scikit-image=0.15.0
  - scipy=1.3.1
  - tqdm=4.32.1
  - numpy==1.17.2
  - opencv=3.4.2
  - librosa=0.7.1
  - jupyterlab=1.1.4
  - jupyterlab_server=1.0.6
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - pytorch
  - tensorflow=1.13.2
  - torchvision
  - pytest
  - gdown