name: testenv
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6.9
  - numba=0.45.1
  - scikit-image=0.15.0
  - scipy=1.3.1
  - tqdm=4.32.1
  - numpy==1.17.2
  - opencv=3.4.2
  - librosa=0.7.1=py_0
  - jupyterlab=1.1.4=pyhf63ae98_0
  - jupyterlab_server=1.0.6=py_0
  - keras=2.3.1=py36_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_0
  - pytorch
  - torchvision
  - pytest
  - tensorflow
  - gdown